ReceteX/ReceteX.Web/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using ReceteX.Models;
using ReceteX.Repository.Shared.Abstract;

namespace ReceteX.Web.Controllers
{
    public class CustomerController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

		public CustomerController(IUnitOfWork unitOfWork)
		{
			this.unitOfWork = unitOfWork;
		}

		public IActionResult Index()
        {
            return View();
        }


        public IActionResult GetAll() 
        {
            return Json(new { data = unitOfWork.Customers.GetAllWithUserCount()});
        
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            //programımızda bir şey silecekken id ile siliyoruz. Reposirtoryde düzenleme yaptık
            unitOfWork.Customers.Remove(id);
            unitOfWork.Save();
            return Ok();
        }

        [HttpPost]
        public IActionResult Create(Customer customer)
        
        {
            unitOfWork.Customers.Add(customer);
            unitOfWork.Save();
            return Ok();
        }
      

        [HttpPost]
        public IActionResult Update(Customer customer) 
        {
            Customer asil = unitOfWork.Customers.GetFirstOrDefault(c=>c.Id == customer.Id);
            asil.Name = customer.Name;
            unitOfWork.Customers.Update(customer);  

            unitOfWork.Save();
            return Ok();
            
        }

        [HttpPost]

        public IActionResult GetById(Guid id)

        {
            return Json(unitOfWork.Customers.GetById(id));
        }
    }
}

ReceteX/ReceteX.Web/Controllers/DiagnosisController.cs
using Microsoft.AspNetCore.Mvc;
using ReceteX.Models;
using ReceteX.Repository.Shared.Abstract;
using ReceteX.Utility;
using System.Xml;

namespace ReceteX.Web.Controllers
{
    public class DiagnosisController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly XmlRetriever xmlRetriever;
		public DiagnosisController(IUnitOfWork unitOfWork, XmlRetriever xmlRetriever)
		{
			this.unitOfWork = unitOfWork;
			this.xmlRetriever = xmlRetriever;
		}

		public IActionResult Index()
        {
            return View();
        }

        public async Task ParseAndSaveFromXml(string xmlContent)
        {

            XmlDocument xmlDoc = new XmlDocument();
            XmlNodeList diagnoses = xmlDoc.SelectNodes("/tanilar/tani");


            foreach (XmlNode diagnosis in diagnoses)
            {
                Diagnosis dia = new Diagnosis();

                dia.Name = diagnosis.SelectSingleNode("ad").InnerText;
                dia.Code = diagnosis.SelectSingleNode("kod").InnerText;
                unitOfWork.Diagnoses.Add(dia);
            }
            unitOfWork.Save();
        }


        public async Task<IActionResult> UpdateDiagnosesList()
        {
            string content = await xmlRetriever.GetXmlContent("https://www.ibys.com.tr/exe/tanilar.xml");

            await ParseAndSaveFromXml(content);

            return RedirectToAction("Index"); 
        }


    }
}

ReceteX/ReceteX.Web/Controllers/MedicineController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReceteX.Models;
using ReceteX.Repository.Shared.Abstract;
using ReceteX.Utility;
using System.Xml;

namespace ReceteX.Web.Controllers
{
    public class MedicineController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly XmlRetriever xmlRetriever;
        //parametre olarak ekledik

        public MedicineController(IUnitOfWork unitOfWork, XmlRetriever xmlRetriever)
        {
            this.unitOfWork = unitOfWork;
            this.xmlRetriever = xmlRetriever;
        }

        public IActionResult Index()
        {
            return View();
        }

        //ayıklayacak
        public async Task ParseAndSaveFromXml(string xmlContent)
        {
            XmlDocument xmlDoc = new XmlDocument();
            xmlDoc.LoadXml(xmlContent);

            //ilaçların altındaki her bir ilaç için
            XmlNodeList medicinesFromXml = xmlDoc.SelectNodes("/ilaclar/ilac");
            //databasedeki tüm aktif nesneler
            IQueryable<Medicine> medicinesFromDb = unitOfWork.Medicines.GetAll().AsNoTracking().OrderBy(m => m.Name).ToList().AsQueryable<Medicine>();
            //database'deki tüm silinmiş nesneler
            IQueryable<Medicine> deletedMedicinesFromDb = unitOfWork.Medicines.GetAllDeleted().AsNoTracking().OrderBy(m => m.Name).ToList().AsQueryable<Medicine>();


            //Case 1 :
            //Yeni kayıtları aktaran döngümüz.
            foreach (XmlNode medicine in medicinesFromXml)
            {
                string barcodeFromXml = medicine.SelectSingleNode("barkod").InnerText;

                //Bu barkoda sahip en az bir kayıt var mı any ile yapıyoruz
                if (!medicinesFromDb.Any(m => m.Barcode == barcodeFromXml))
                {
                    Medicine med = new Medicine();
                    med.Name = medicine.SelectSingleNode("ad").InnerText;
                    med.Barcode = barcodeFromXml;
                    unitOfWork.Medicines.Add(med);

                    //Her seferinde save changes yapmıyorum, memoryde 8.000 tane çalışıyor
                }

                else
                {
                    Medicine medSilinmis = deletedMedicinesFromDb.FirstOrDefault(m => m.Barcode == barcodeFromXml);
                    if (medSilinmis != null)
                    {
                        medSilinmis.isDeleted = false;
                        unitOfWork.Medicines.Update(medSilinmis);
                    }
                }
            }
            //Hepsi bittikten sonra yapıyorum
            unitOfWork.Save();



            //Kaynaktan silinmiş olan ilaçları databasede isdelete=true yapan döngümüz
            //XmlNodeListe extension methodla sorgu atamıyoruz modifiye ederek yapıyoruz

            IEnumerable<XmlNode> medicinesFromXmlEnumarable =xmlDoc.SelectNodes("/ilaclar/ilac").Cast<XmlNode>();
            foreach (Medicine ilac in medicinesFromDb)
            {
               if(!medicinesFromXmlEnumarable.Any(x=>x.SelectSingleNode("barkod").InnerText==ilac.Barcode))
                {
                    //remove metodu zaten isDeleted true hale getiriyor denedik ama bu seferde db çok yordu
                    //ilac.isDeleted=true;
                    //remove metodu sadece guid id alıyor
                    //unitOfWork.Medicines.Remove(ilac.Id);

                    ilac.isDeleted = true;
                    unitOfWork.Medicines.Update(ilac);
                    
                }
                
            }


            unitOfWork.Save();
        }

        public async Task<IActionResult> UpdateMedicinesList()
        {
            //yapacağı işler bitince sayfaya gidince sayfaya yönlensin
            //ajax kullanmaycağım çok fazla data var

            // Case 1 :
            // string content = await xmlRetriever.GetXmlContent("https://www.ibys.com.tr/exe/ilaclar.xml");

            //Case 2 :
            //bakanlıkta olmayıp bizde olanları tespit etmek için yaptık
            string content = await xmlRetriever.GetXmlContent("https://www.ibys.com.tr/exe/ilaclar.xml");
            await ParseAndSaveFromXml(content);

            //Bu şekilde tek satırda da yazabiliriz.
            //await ParseAndSaveFromXml(await xmlRetriever.GetXmlContent("https://www.ibys.com.tr/exe/ilaclar.xml"));
            return RedirectToAction("Index");
        }
    }
}

ReceteX/ReceteX.Web/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8" />
    <title>Kütüphane.NET</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- App favicon -->
    <link rel="shortcut icon" href="~/assets/images/favicon.ico">

    <!-- Bootstrap Css -->
    <link href="~/assets/css/bootstrap.min.css" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="~/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="~/assets/css/app.min.css" id="app-style" rel="stylesheet" type="text/css" />

    <!-- Sweet Alert-->
    <link href="~/assets/libs/sweetalert2/sweetalert2.min.css" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" type="text/css" href="assets/libs/toastr/build/toastr.min.css">


    <!-- DataTables -->
    <link href="~/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <!-- plugin css -->
    <link href="~/assets/libs/select2/css/select2.min.css" rel="stylesheet" type="text/css" />


    @await RenderSectionAsync("Styles", false);
</head>


<body>

    <!-- <body data-layout="horizontal" data-topbar="colored"> -->
    <!-- Begin page -->
    <div id="layout-wrapper">


        <header id="page-topbar">
            <div class="navbar-header">
                <div class="d-flex">
                    <!-- LOGO -->
                    <div class="navbar-brand-box">
                        <a href="index.html" class="logo logo-dark">
                            <span class="logo-sm">
                                <img src="~/assets/images/logo-sm.png" alt="" height="22">
                            </span>
                            <span class="logo-lg">
                                <img src="~/assets/images/logo-dark.png" alt="" height="20">
                            </span>
                        </a>

                        <a href="index.html" class="logo logo-light">
                            <span class="logo-sm">
                                <img src="~/assets/images/logo-sm.png" alt="" height="22">
                            </span>
                            <span class="logo-lg">
                                <img src="~/assets/images/logo-light.png" alt="" height="20">
                            </span>
                        </a>
                    </div>

                    <button type="button" class="btn btn-sm px-3 font-size-16 header-item waves-effect vertical-menu-btn">
                        <i class="fa fa-fw fa-bars"></i>
                    </button>

                    <!-- App Search-->
                    <form class="app-search d-none d-lg-block">
                        <div class="position-relative">
                            <input type="text" class="form-control" placeholder="Search...">
                            <span class="uil-search"></span>
                        </div>
                    </form>
                </div>

                <div class="d-flex">

                    <div class="dropdown d-inline-block d-lg-none ms-2">
                        <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown"
                                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="uil-search"></i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0"
                             aria-labelledby="page-header-search-dropdown">

                            <form class="p-3">
                                <div class="m-0">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search ..." aria-label="Recipient's username">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="submit"><i class="mdi mdi-magnify"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>



                    <div class="dropdown d-none d-lg-inline-block ms-1">
                        <button type="button" class="btn header-item noti-icon waves-effect" data-bs-toggle="fullscreen">
                            <i class="uil-minus-path"></i>
                        </button>
                    </div>



                    <div class="dropdown d-inline-block">
                        <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img class="rounded-circle header-profile-user" src="~/assets/images/users/avatar-4.jpg"
                                 alt="Header Avatar">
                            <span class="d-none d-xl-inline-block ms-1 fw-medium font-size-15">
                                @User.FindFirstValue(ClaimTypes.Name)
                            </span>
                            <i class="uil-angle-down d-none d-xl-inline-block font-size-15"></i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-end">
                            <!-- item-->

                            <a class="dropdown-item" asp-controller="User" asp-action="Logout"><i class="uil uil-sign-out-alt font-size-18 align-middle me-1 text-muted"></i> <span class="align-middle">Çıkış Yap</span></a>
                        </div>
                    </div>



                </div>
            </div>
        </header>
        <!-- ========== Left Sidebar Start ========== -->
        <div class="vertical-menu">

            <!-- LOGO -->
            <div class="navbar-brand-box">
                <a href="index.html" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="assets/images/logo-sm.png" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="assets/images/logo-dark.png" alt="" height="20">
                    </span>
                </a>

                <a href="index.html" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="assets/images/logo-sm.png" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="assets/images/logo-light.png" alt="" height="20">
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 header-item waves-effect vertical-menu-btn">
                <i class="fa fa-fw fa-bars"></i>
            </button>

            <div data-simplebar class="sidebar-menu-scroll">

                <!--- Sidemenu -->
                <div id="sidebar-menu">
                    <!-- Left Menu Start -->
                    <ul class="metismenu list-unstyled" id="side-menu">
                        <li class="menu-title">Menu</li>

                        <li>
                            <a asp-action="Index" asp-controller="Home">
                                <i class="uil-home-alt"></i><span class="badge rounded-pill bg-primary float-end">01</span>
                                <span>Ana Sayfa</span>
                            </a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li>
                                <a asp-action="Index" asp-controller="User">
                                    <i class="uil-home-alt"></i>
                                    <span>Kullanıcı Yönetimi</span>
                                </a>
                            </li>
                        }

                        <li>
                            <a href="javascript: void(0);" class="has-arrow waves-effect">
                                <i class="uil-window-section"></i>
                                <span>Yönetsel</span>
                            </a>
                            <ul class="sub-menu" aria-expanded="true">
                                <li><a asp-controller="User" asp-action="Index">Kullanıcılar</a></li>


                                <li><a asp-controller="Customer" asp-action="Index">Müşteriler</a></li>
                                <li><a asp-controller="Medicine" asp-action="Index">İlaç Listesi</a></li>
                                <li><a asp-controller="Diagnosis" asp-action="Index">Tanı Listesi</a></li>
                            </ul>
                        </li>

                    </ul>
                </div>
                <!-- Sidebar -->
            </div>
        </div>
        <!-- Left Sidebar End -->
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">

            <div class="page-content">
                <div class="container-fluid">
                    @RenderBody()
                </div> <!-- container-fluid -->
            </div>
            <!-- End Page-content -->

         

            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <script>document.write(new Date().getFullYear())</script> © Minible.
                        </div>
                        <div class="col-sm-6">
                            <div class="text-sm-end d-none d-sm-block">
                                Crafted with <i class="mdi mdi-heart text-danger"></i> by <a href="https://themesbrand.com/" target="_blank" class="text-reset">Themesbrand</a>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        <!-- end main content-->

    </div>
    <!-- END layout-wrapper -->
    <!-- Right Sidebar -->
    <!-- /Right-bar -->
    <!-- Right bar overlay-->
    <!-- JAVASCRIPT -->
    <script src="~/assets/libs/jquery/jquery.min.js"></script>
    <script src="~/assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/libs/metismenu/metisMenu.min.js"></script>
    <script src="~/assets/libs/simplebar/simplebar.min.js"></script>
    <script src="~/assets/libs/node-waves/waves.min.js"></script>
    <script src="~/assets/libs/waypoints/lib/jquery.waypoints.min.js"></script>
    <script src="~/assets/libs/jquery.counterup/jquery.counterup.min.js"></script>

    <!-- Required datatable js -->
    <script src="~/assets/libs/datatables.net/js/jquery.dataTables.min.js"></script>
    <!-- plugins -->
    <script src="~/assets/libs/select2/js/select2.min.js"></script>

    <!-- Sweet Alerts js -->
    <script src="~/assets/libs/sweetalert2/sweetalert2.min.js"></script>

    <!-- toastr plugin -->
    <script src="~/assets/libs/toastr/build/toastr.min.js"></script>

    <!-- App js -->
    <script src="~/assets/js/app.js"></script>

    @await RenderSectionAsync("Scripts", false);

</body>

</html>