ReceteX/ReceteX.Web/Controllers/DiagnosisController.cs
using Microsoft.AspNetCore.Mvc;
using ReceteX.Models;
using ReceteX.Repository.Shared.Abstract;
using ReceteX.Utility;
using System.Xml;

namespace ReceteX.Web.Controllers
{
    public class DiagnosisController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly XmlRetriever xmlRetriever;
		public DiagnosisController(IUnitOfWork unitOfWork, XmlRetriever xmlRetriever)
		{
			this.unitOfWork = unitOfWork;
			this.xmlRetriever = xmlRetriever;
		}

		public IActionResult Index()
        {
            return View();
        }

        public async Task ParseAndSaveFromXml(string xmlContent)
        {

            XmlDocument xmlDoc = new XmlDocument();
            XmlNodeList diagnoses = xmlDoc.SelectNodes("/tanilar/tani");


            foreach (XmlNode diagnosis in diagnoses)
            {
                Diagnosis dia = new Diagnosis();

                dia.Name = diagnosis.SelectSingleNode("ad").InnerText;
                dia.Code = diagnosis.SelectSingleNode("kod").InnerText;
                unitOfWork.Diagnoses.Add(dia);
            }
            unitOfWork.Save();
        }


        public async Task<IActionResult> UpdateDiagnosesList()
        {
            string content = await xmlRetriever.GetXmlContent("https://www.ibys.com.tr/exe/tanilar.xml");

            await ParseAndSaveFromXml(content);

            return RedirectToAction("Index"); 
        }


    }
}

ReceteX/ReceteX.Web/Controllers/PrescriptionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReceteX.Models;
using ReceteX.Repository.Shared.Abstract;
using System.Security.Claims;

namespace ReceteX.Web.Controllers
{
    [Authorize]
    public class PrescriptionController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public PrescriptionController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }


        public IActionResult Index()
        {
            Prescription prescription = new Prescription();
            prescription.StatusId = unitOfWork.Statuses.GetFirstOrDefault(s => s.Name == "Taslak").Id;
            prescription.AppUserId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            unitOfWork.Prescriptions.Add(prescription);
            unitOfWork.Save();
            return View(prescription);


        }


        [HttpPost]
        public IActionResult Create(Prescription prescription)
        {
            unitOfWork.Prescriptions.Add(prescription);
            unitOfWork.Save();

            return Json(prescription);
        }

        [HttpPost]
        //reçeteye tanı ekleyeceğiz
        public IActionResult AddDiagnosis(Guid prescriptionId, Guid diagnosisId)
        {
            Prescription asil = unitOfWork.Prescriptions.GetAll(p => p.Id == prescriptionId).Include(p => p.Diagnoses).First();
            Diagnosis asilDiagnosis = unitOfWork.Diagnoses.GetFirstOrDefault(d => d.Id == diagnosisId);

            asil.Diagnoses.Add(asilDiagnosis);
            unitOfWork.Prescriptions.Update(asil);
            unitOfWork.Save();

            return Ok();

        }

        [HttpPost]
        public IActionResult GetDiagnoses(Guid prescriptionId)
        {
            return Json(unitOfWork.Prescriptions.GetAll(p => p.Id == prescriptionId).Include(p => p.Diagnoses));

        }

        [HttpPost]
        public IActionResult AddDescription(Guid prescriptionId, Description description)
        {
            Prescription asil = unitOfWork.Prescriptions.GetFirstOrDefault(p => p.Id == prescriptionId);
            asil.Descriptions.Add(description);
            unitOfWork.Prescriptions.Update(asil);
            unitOfWork.Save();
            return Ok();
        }

        [HttpPost]
        public IActionResult AddMedicine(Guid prescriptionId, PrescriptionMedicine prescriptionMedicine)
        {
            Prescription asil = unitOfWork.Prescriptions.GetFirstOrDefault(p => p.Id == prescriptionId);
            asil.PrescriptionMedicines.Add(prescriptionMedicine);
            unitOfWork.Prescriptions.Update(asil);
            unitOfWork.Save();
            return Ok();

        }

        [HttpPost]
        public IActionResult RemoveMedicine(Guid prescriptionId, Guid prescriptionMedicineId)
        {

            Prescription asil = unitOfWork.Prescriptions.GetFirstOrDefault(p => p.Id == prescriptionId);

            asil.PrescriptionMedicines.Remove(asil.PrescriptionMedicines.FirstOrDefault(pm => pm.Id == prescriptionMedicineId));

            unitOfWork.Prescriptions.Update(asil);
            unitOfWork.Save();
            return Ok();

        }

        [HttpPost]
        public IActionResult RemoveDescription(Guid prescriptionId, Guid descriptionId)
        {
            Prescription asil = unitOfWork.Prescriptions.GetFirstOrDefault(p => p.Id == prescriptionId);
            asil.Descriptions.Remove(asil.Descriptions.FirstOrDefault(d => d.Id == descriptionId));

            unitOfWork.Prescriptions.Update(asil);
            unitOfWork.Save();
            return Ok();

        }

        [HttpPost]
        public IActionResult RemoveDiagnosis(Guid prescriptionId, Guid diagnosisId)
        {
            Prescription asil = unitOfWork.Prescriptions.GetFirstOrDefault(p => p.Id == prescriptionId);
            asil.Diagnoses.Remove(asil.Diagnoses.FirstOrDefault(d => d.Id == diagnosisId));

            unitOfWork.Prescriptions.Update(asil);
            unitOfWork.Save();
            return Ok();

        }



    }
}

//GET: GET isteği, belirtilen bir kaynağın(örneğin bir web sayfası veya bir veri) alınmasını istemek için kullanılır. Bu yöntem, sunucudan veriyi almak için kullanılır ve genellikle bir kaynağın okunması veya görüntülenmesi için kullanılır. GET istekleri genellikle URL üzerinden parametrelerle iletilir ve verilerin sunucudan alınmasını sağlar.

//POST: POST isteği, sunucuya veri göndermek için kullanılır. Bu yöntem, bir kaynağa yeni bir veri eklemek veya mevcut bir kaynağı değiştirmek için kullanılır. POST istekleri genellikle bir formun sunucuya gönderilmesi veya bir API'ye veri gönderilmesi gibi durumlarda kullanılır.

//PUT: PUT isteği, belirtilen bir kaynağı güncellemek için kullanılır. Bu yöntem, belirli bir URL'deki kaynağın tamamen değiştirilmesini sağlar. Bir PUT isteği gönderildiğinde, sunucu istekte belirtilen kaynağı günceller veya oluşturur.

//DELETE: DELETE isteği, belirtilen bir kaynağı silmek için kullanılır. Bu yöntem, bir URL'deki kaynağın sunucu tarafından silinmesini sağlar. DELETE isteği gönderildiğinde, sunucu istekte belirtilen kaynağı siler.

ReceteX/ReceteX.Web/Views/Prescription/Index.cshtml
@using ReceteX.Models;
@model Prescription


@section Styles{

    <link rel="stylesheet" href="http://code.query.com/ui/1.12.1/themes/base/jquery-ui.css"/>

    <style>

        .ui.autocomplete-loading {
            background : white url("/assets/images/loading.gif) center center no repeat;
        }



        .ui-autocomplete .ui-menu-item {
            padding : 8px 12px;
            cursor : pointer;
            text-align:center;

        }

        .ui.ui-autocomplete .ui-state-active {
            background-color:#007bff;
            color : #fff;
        }


    </style>


}




    <div>
    
        <div class="card"> 

            <div class="card-header text-white bg-success bg-pardient text-center"> 

                <span class="fs-6">Tanı Ekleme Bölümü</span>  
            </div>
            <div class="ui-widget">
            <input type="text" id="diagnosis" name="diagnosis" class="form-control text-center" placeholder="Tanı adının veya kodunun en az ilk 3 harfini yazınız, sonra listeden seçiniz..."/>
            <input type="hidden" id="diagnosisId" name="diagnosisId" />
            </div>
            <div id="divDiagnoses" class="texxt-md-center mt-3">
            </div>


        </div>
    </div>


    @section Scripts{

        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


        function fillDiagnoses()

        {
            $.ajax({
                type:'POST',
                url:'@Url.Action("GetDiagnoses", "Prescription")',

                success:function(res){
                    $('#divDiagnoses').empty();
                    for(var diagnose of res[0].diagnoses)
                    $("#divDiagnoses").append(`<div>${diagnose.name}</div>`);
                
                
                }
            });
        }

        function addDiagnosis(diagnosisId){
            $.ajax({
                type:'POST',
                url:'@Url.Action("AddDiagnosis","Prescription")',
                data:{
                    prescriptionId:'@Model.Id', diagnosisId:diagnosisId},
                success:function(res) {
                    fillDiagnoses();
                }

            });
        }

        $(function(){
            $("#diagnosis").autocomplete({
                source : function (request, response){
                    $.ajax({

                      url: '@Url.Action("SearchDiagnosis","Diagnosis" )',

                      data:{searchTerm : request.term},
                      dataType:"json",
                      type:"GET",
                      success: function(data){
                        response($.map(data, function(item){
                            return
                            {
                                label : item.name,
                                value: item.id
                            };
                        }));
                      }
                    });
                },

                minLength:3,
                select: function(event, ui){
                    $("#diagnosis").val('');
                    $("#diagnosisId").val(ui.item.value);
                    addDiagnosis(ui.item.value);
                    return false;

                }
            });
        });
    }